-- Wireshark Lua Dissector
-- Generated by protococo from .coco file

local Protocol_values = {
    [1] = "ICMP",
    [6] = "TCP",
    [17] = "UDP",
}
local IcmpType_values = {
    [0] = "ECHO_REPLY",
    [3] = "DEST_UNREACHABLE",
    [4] = "SOURCE_QUENCH",
    [5] = "REDIRECT",
    [8] = "ECHO_REQUEST",
    [11] = "TIME_EXCEEDED",
    [12] = "PARAMETER_PROBLEM",
    [13] = "TIMESTAMP_REQUEST",
    [14] = "TIMESTAMP_REPLY",
}
local TcpFlags_values = {
    [1] = "FIN",
    [2] = "SYN",
    [4] = "RST",
    [8] = "PSH",
    [16] = "ACK",
    [32] = "URG",
    [64] = "ECE",
    [128] = "CWR",
    [18] = "SYN_ACK",
    [17] = "FIN_ACK",
    [24] = "PSH_ACK",
    [20] = "RST_ACK",
}
local EtherType_values = {
    [2048] = "IPV4",
    [2054] = "ARP",
    [33024] = "VLAN",
    [34525] = "IPV6",
}

-- Protocol: ipv4_packet
local ipv4_packet_proto = Proto("ipv4_packet", "Ipv4 Packet")

-- Fields
local f_ipv4_packet_header_version_ihl_ihl = ProtoField.uint8("ipv4_packet.header.version_ihl.ihl", "ihl", base.DEC, nil, 0xF0)
local f_ipv4_packet_header_version_ihl_version = ProtoField.uint8("ipv4_packet.header.version_ihl.version", "version", base.DEC, nil, 0x0F)
local f_ipv4_packet_header_dscp_ecn = ProtoField.uint8("ipv4_packet.header.dscp_ecn", "dscp_ecn", base.DEC)
local f_ipv4_packet_header_total_length = ProtoField.uint16("ipv4_packet.header.total_length", "total_length", base.DEC)
local f_ipv4_packet_header_identification = ProtoField.uint16("ipv4_packet.header.identification", "identification", base.DEC)
local f_ipv4_packet_header_flags_fragment = ProtoField.uint16("ipv4_packet.header.flags_fragment", "flags_fragment", base.DEC)
local f_ipv4_packet_header_ttl = ProtoField.uint8("ipv4_packet.header.ttl", "ttl", base.DEC)
local f_ipv4_packet_header_protocol = ProtoField.uint8("ipv4_packet.header.protocol", "protocol", base.DEC, Protocol_values)
local f_ipv4_packet_header_header_checksum = ProtoField.uint16("ipv4_packet.header.header_checksum", "header_checksum", base.DEC)
local f_ipv4_packet_header_src_ip = ProtoField.ipv4("ipv4_packet.header.src_ip", "src_ip", nil)
local f_ipv4_packet_header_dst_ip = ProtoField.ipv4("ipv4_packet.header.dst_ip", "dst_ip", nil)
-- f_ipv4_packet_header: embedded message ipv4_header
local f_ipv4_packet_payload = ProtoField.bytes("ipv4_packet.payload", "payload")
local f_ipv4_packet_payload_tcp_src_port = ProtoField.uint16("ipv4_packet.payload.tcp.src_port", "src_port", base.DEC)
local f_ipv4_packet_payload_tcp_dst_port = ProtoField.uint16("ipv4_packet.payload.tcp.dst_port", "dst_port", base.DEC)
local f_ipv4_packet_payload_tcp_seq_num = ProtoField.uint32("ipv4_packet.payload.tcp.seq_num", "seq_num", base.DEC)
local f_ipv4_packet_payload_tcp_ack_num = ProtoField.uint32("ipv4_packet.payload.tcp.ack_num", "ack_num", base.DEC)
local f_ipv4_packet_payload_tcp_data_offset_reserved_reserved = ProtoField.uint8("ipv4_packet.payload.tcp.data_offset_reserved.reserved", "reserved", base.DEC, nil, 0xF0)
local f_ipv4_packet_payload_tcp_data_offset_reserved_data_offset = ProtoField.uint8("ipv4_packet.payload.tcp.data_offset_reserved.data_offset", "data_offset", base.DEC, nil, 0x0F)
local f_ipv4_packet_payload_tcp_flags = ProtoField.uint8("ipv4_packet.payload.tcp.flags", "flags", base.DEC, TcpFlags_values)
local f_ipv4_packet_payload_tcp_window = ProtoField.uint16("ipv4_packet.payload.tcp.window", "window", base.DEC)
local f_ipv4_packet_payload_tcp_checksum = ProtoField.uint16("ipv4_packet.payload.tcp.checksum", "checksum", base.DEC)
local f_ipv4_packet_payload_tcp_urgent_ptr = ProtoField.uint16("ipv4_packet.payload.tcp.urgent_ptr", "urgent_ptr", base.DEC)
local f_ipv4_packet_payload_tcp_data = ProtoField.bytes("ipv4_packet.payload.tcp.data", "data")
-- f_ipv4_packet_payload_tcp: embedded message tcp_segment
local f_ipv4_packet_payload_udp_src_port = ProtoField.uint16("ipv4_packet.payload.udp.src_port", "src_port", base.DEC)
local f_ipv4_packet_payload_udp_dst_port = ProtoField.uint16("ipv4_packet.payload.udp.dst_port", "dst_port", base.DEC)
local f_ipv4_packet_payload_udp_length = ProtoField.uint16("ipv4_packet.payload.udp.length", "length", base.DEC)
local f_ipv4_packet_payload_udp_checksum = ProtoField.uint16("ipv4_packet.payload.udp.checksum", "checksum", base.DEC)
local f_ipv4_packet_payload_udp_data = ProtoField.bytes("ipv4_packet.payload.udp.data", "data")
-- f_ipv4_packet_payload_udp: embedded message udp_datagram
local f_ipv4_packet_payload_icmp_icmp_type = ProtoField.uint8("ipv4_packet.payload.icmp.icmp_type", "icmp_type", base.DEC, IcmpType_values)
local f_ipv4_packet_payload_icmp_code = ProtoField.uint8("ipv4_packet.payload.icmp.code", "code", base.DEC)
local f_ipv4_packet_payload_icmp_checksum = ProtoField.uint16("ipv4_packet.payload.icmp.checksum", "checksum", base.DEC)
local f_ipv4_packet_payload_icmp_identifier = ProtoField.uint16("ipv4_packet.payload.icmp.identifier", "identifier", base.DEC)
local f_ipv4_packet_payload_icmp_sequence = ProtoField.uint16("ipv4_packet.payload.icmp.sequence", "sequence", base.DEC)
local f_ipv4_packet_payload_icmp_data = ProtoField.bytes("ipv4_packet.payload.icmp.data", "data")
-- f_ipv4_packet_payload_icmp: embedded message icmp_message

ipv4_packet_proto.fields = {
    f_ipv4_packet_header_version_ihl_ihl,
    f_ipv4_packet_header_version_ihl_version,
    f_ipv4_packet_header_dscp_ecn,
    f_ipv4_packet_header_total_length,
    f_ipv4_packet_header_identification,
    f_ipv4_packet_header_flags_fragment,
    f_ipv4_packet_header_ttl,
    f_ipv4_packet_header_protocol,
    f_ipv4_packet_header_header_checksum,
    f_ipv4_packet_header_src_ip,
    f_ipv4_packet_header_dst_ip,
    f_ipv4_packet_payload,
    f_ipv4_packet_payload_tcp_src_port,
    f_ipv4_packet_payload_tcp_dst_port,
    f_ipv4_packet_payload_tcp_seq_num,
    f_ipv4_packet_payload_tcp_ack_num,
    f_ipv4_packet_payload_tcp_data_offset_reserved_reserved,
    f_ipv4_packet_payload_tcp_data_offset_reserved_data_offset,
    f_ipv4_packet_payload_tcp_flags,
    f_ipv4_packet_payload_tcp_window,
    f_ipv4_packet_payload_tcp_checksum,
    f_ipv4_packet_payload_tcp_urgent_ptr,
    f_ipv4_packet_payload_tcp_data,
    f_ipv4_packet_payload_udp_src_port,
    f_ipv4_packet_payload_udp_dst_port,
    f_ipv4_packet_payload_udp_length,
    f_ipv4_packet_payload_udp_checksum,
    f_ipv4_packet_payload_udp_data,
    f_ipv4_packet_payload_icmp_icmp_type,
    f_ipv4_packet_payload_icmp_code,
    f_ipv4_packet_payload_icmp_checksum,
    f_ipv4_packet_payload_icmp_identifier,
    f_ipv4_packet_payload_icmp_sequence,
    f_ipv4_packet_payload_icmp_data,
}

function ipv4_packet_proto.dissector(buffer, pinfo, tree)
    pinfo.cols.protocol = "ipv4_packet"

    local subtree = tree:add(ipv4_packet_proto, buffer(), "ipv4_packet")
    local offset = 0

    -- Embedded: header (ipv4_header)
    local header_start = offset
    local header_tree = subtree:add(buffer(offset), "header")
    -- Bitfield: version_ihl
    header_tree:add(f_ipv4_packet_header_version_ihl_ihl, buffer(offset, 1))
    header_tree:add(f_ipv4_packet_header_version_ihl_version, buffer(offset, 1))
    local ihl = bit.band(bit.rshift(buffer(offset, 1):uint(), 4), 15)
    local version = bit.band(bit.rshift(buffer(offset, 1):uint(), 0), 15)
    offset = offset + 1

    local dscp_ecn = buffer(offset, 1):uint()
    header_tree:add(f_ipv4_packet_header_dscp_ecn, buffer(offset, 1))
    offset = offset + 1

    local total_length = buffer(offset, 2):uint()
    header_tree:add(f_ipv4_packet_header_total_length, buffer(offset, 2))
    offset = offset + 2

    local identification = buffer(offset, 2):uint()
    header_tree:add(f_ipv4_packet_header_identification, buffer(offset, 2))
    offset = offset + 2

    local flags_fragment = buffer(offset, 2):uint()
    header_tree:add(f_ipv4_packet_header_flags_fragment, buffer(offset, 2))
    offset = offset + 2

    local ttl = buffer(offset, 1):uint()
    header_tree:add(f_ipv4_packet_header_ttl, buffer(offset, 1))
    offset = offset + 1

    local protocol = buffer(offset, 1):uint()
    header_tree:add(f_ipv4_packet_header_protocol, buffer(offset, 1))
    offset = offset + 1

    local header_checksum = buffer(offset, 2):uint()
    header_tree:add(f_ipv4_packet_header_header_checksum, buffer(offset, 2))
    offset = offset + 2

    local src_ip = buffer(offset, 4):ipv4()
    header_tree:add(f_ipv4_packet_header_src_ip, buffer(offset, 4))
    offset = offset + 4

    local dst_ip = buffer(offset, 4):ipv4()
    header_tree:add(f_ipv4_packet_header_dst_ip, buffer(offset, 4))
    offset = offset + 4

    header_tree:set_len(offset - header_start)

    local payload_len = (total_length - 20)
    local payload_buf = buffer(offset, payload_len)
    local payload_tree = subtree:add(f_ipv4_packet_payload, payload_buf)
    offset = offset + payload_len

    -- Match on header.protocol
    local payload_offset = 0
    if protocol == 6 then
        local tcp_tree = payload_tree:add(payload_buf(payload_offset), "tcp")
        local src_port = payload_buf(payload_offset, 2):uint()
        tcp_tree:add(f_ipv4_packet_payload_tcp_src_port, payload_buf(payload_offset, 2))
        payload_offset = payload_offset + 2
        local dst_port = payload_buf(payload_offset, 2):uint()
        tcp_tree:add(f_ipv4_packet_payload_tcp_dst_port, payload_buf(payload_offset, 2))
        payload_offset = payload_offset + 2
        local seq_num = payload_buf(payload_offset, 4):uint()
        tcp_tree:add(f_ipv4_packet_payload_tcp_seq_num, payload_buf(payload_offset, 4))
        payload_offset = payload_offset + 4
        local ack_num = payload_buf(payload_offset, 4):uint()
        tcp_tree:add(f_ipv4_packet_payload_tcp_ack_num, payload_buf(payload_offset, 4))
        payload_offset = payload_offset + 4
        tcp_tree:add(f_ipv4_packet_payload_tcp_data_offset_reserved_reserved, payload_buf(payload_offset, 1))
        tcp_tree:add(f_ipv4_packet_payload_tcp_data_offset_reserved_data_offset, payload_buf(payload_offset, 1))
        payload_offset = payload_offset + 1
        local flags = payload_buf(payload_offset, 1):uint()
        tcp_tree:add(f_ipv4_packet_payload_tcp_flags, payload_buf(payload_offset, 1))
        payload_offset = payload_offset + 1
        local window = payload_buf(payload_offset, 2):uint()
        tcp_tree:add(f_ipv4_packet_payload_tcp_window, payload_buf(payload_offset, 2))
        payload_offset = payload_offset + 2
        local checksum = payload_buf(payload_offset, 2):uint()
        tcp_tree:add(f_ipv4_packet_payload_tcp_checksum, payload_buf(payload_offset, 2))
        payload_offset = payload_offset + 2
        local urgent_ptr = payload_buf(payload_offset, 2):uint()
        tcp_tree:add(f_ipv4_packet_payload_tcp_urgent_ptr, payload_buf(payload_offset, 2))
        payload_offset = payload_offset + 2
        tcp_tree:add(f_ipv4_packet_payload_tcp_data, payload_buf(payload_offset))
    elseif protocol == 17 then
        local udp_tree = payload_tree:add(payload_buf(payload_offset), "udp")
        local src_port = payload_buf(payload_offset, 2):uint()
        udp_tree:add(f_ipv4_packet_payload_udp_src_port, payload_buf(payload_offset, 2))
        payload_offset = payload_offset + 2
        local dst_port = payload_buf(payload_offset, 2):uint()
        udp_tree:add(f_ipv4_packet_payload_udp_dst_port, payload_buf(payload_offset, 2))
        payload_offset = payload_offset + 2
        local length = payload_buf(payload_offset, 2):uint()
        udp_tree:add(f_ipv4_packet_payload_udp_length, payload_buf(payload_offset, 2))
        payload_offset = payload_offset + 2
        local checksum = payload_buf(payload_offset, 2):uint()
        udp_tree:add(f_ipv4_packet_payload_udp_checksum, payload_buf(payload_offset, 2))
        payload_offset = payload_offset + 2
        local data_len = (length - 8)
        udp_tree:add(f_ipv4_packet_payload_udp_data, payload_buf(payload_offset, data_len))
        payload_offset = payload_offset + data_len
    elseif protocol == 1 then
        local icmp_tree = payload_tree:add(payload_buf(payload_offset), "icmp")
        local icmp_type = payload_buf(payload_offset, 1):uint()
        icmp_tree:add(f_ipv4_packet_payload_icmp_icmp_type, payload_buf(payload_offset, 1))
        payload_offset = payload_offset + 1
        local code = payload_buf(payload_offset, 1):uint()
        icmp_tree:add(f_ipv4_packet_payload_icmp_code, payload_buf(payload_offset, 1))
        payload_offset = payload_offset + 1
        local checksum = payload_buf(payload_offset, 2):uint()
        icmp_tree:add(f_ipv4_packet_payload_icmp_checksum, payload_buf(payload_offset, 2))
        payload_offset = payload_offset + 2
        local identifier = payload_buf(payload_offset, 2):uint()
        icmp_tree:add(f_ipv4_packet_payload_icmp_identifier, payload_buf(payload_offset, 2))
        payload_offset = payload_offset + 2
        local sequence = payload_buf(payload_offset, 2):uint()
        icmp_tree:add(f_ipv4_packet_payload_icmp_sequence, payload_buf(payload_offset, 2))
        payload_offset = payload_offset + 2
        icmp_tree:add(f_ipv4_packet_payload_icmp_data, payload_buf(payload_offset))
    else
        -- Default: raw bytes
    end

end

-- Registration
-- To register with IP:
-- local ip_table = DissectorTable.get("ip.proto")
-- ip_table:add(6, ipv4_packet_proto)  -- TCP
-- Or use: Analyze -> Decode As -> ipv4_packet

